# Generated by Django 2.2.7 on 2020-01-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundingboxobject',
            name='taskurl',
        ),
    ]
