# Generated by Django 2.2.7 on 2019-12-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBoxObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=255)),
                ('y', models.CharField(max_length=255)),
                ('l', models.CharField(max_length=255)),
                ('h', models.CharField(max_length=255)),
                ('taskid', models.CharField(max_length=255)),
            ],
        ),
    ]
