# Generated by Django 2.2.7 on 2020-01-16 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_auto_20200112_2136'),
        ('merger', '0002_boundingboxobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundingboxobject',
            name='taskid',
        ),
        migrations.AddField(
            model_name='boundingboxobject',
            name='bb_taskpath',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='distributor.TaskPathBoundingBox'),
            preserve_default=False,
        ),
    ]
