# Generated by Django 2.2.7 on 2020-01-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0002_remove_boundingboxobject_taskurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundingboxobject',
            name='taskurl',
            field=models.CharField(default='null', max_length=2000),
        ),
    ]
