# Generated by Django 2.2.7 on 2020-01-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0003_auto_20200116_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundingboxobject',
            name='bb_taskpath',
        ),
        migrations.AddField(
            model_name='boundingboxobject',
            name='taskPath',
            field=models.CharField(default='null', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boundingboxobject',
            name='taskid',
            field=models.CharField(default='ok', max_length=255),
            preserve_default=False,
        ),
    ]
