# Generated by Django 2.2.7 on 2020-01-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0004_boundingboxobjectnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBoxObjectall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=255)),
                ('y', models.CharField(max_length=255)),
                ('l', models.CharField(max_length=255)),
                ('h', models.CharField(max_length=255)),
                ('taskid', models.CharField(max_length=255)),
                ('taskurl', models.CharField(max_length=2000)),
            ],
        ),
    ]
