import os 

VALID = 5
MAX_QUEUELEN = 4
THRESHOLD_QUEUELEN = MAX_QUEUELEN / 2
TASK_TYPE = 'IMGAAA'

IMG_BASE_DIR = os.path.dirname(os.path.abspath(__file__))

THRESHOLD_VALUE=2
CORRECT_THRESHOLD=0.6
OVERLAP_PERCENT = 0.8
MIN_CLUSTER_LEN = 2
