# Generated by Django 2.2.7 on 2020-01-16 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPath',
            fields=[
                ('taskgivenID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('taskPath', models.CharField(max_length=2000)),
                ('taskTag', models.CharField(max_length=255)),
                ('taskCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPathBoundingBox',
            fields=[
                ('bb_taskgivenID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bb_taskPath', models.CharField(max_length=2000)),
                ('bb_taskTag', models.CharField(max_length=255)),
                ('bb_taskCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProcessedDataBoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=255)),
                ('y', models.CharField(max_length=255)),
                ('l', models.CharField(max_length=255)),
                ('h', models.CharField(max_length=255)),
                ('bb_taskpath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.TaskPathBoundingBox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProcessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.CharField(max_length=255)),
                ('x2', models.CharField(max_length=255)),
                ('x3', models.CharField(max_length=255)),
                ('x4', models.CharField(max_length=255)),
                ('x5', models.CharField(max_length=255)),
                ('y1', models.CharField(max_length=255)),
                ('y2', models.CharField(max_length=255)),
                ('y3', models.CharField(max_length=255)),
                ('y4', models.CharField(max_length=255)),
                ('y5', models.CharField(max_length=255)),
                ('taskpath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.TaskPath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
