# Generated by Django 2.2.7 on 2019-12-21 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPathBoundingBox',
            fields=[
                ('bb_taskgivenID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bb_taskPath', models.ImageField(upload_to='post_images')),
                ('bb_taskCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProcessedDataBoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=255)),
                ('y', models.CharField(max_length=255)),
                ('l', models.CharField(max_length=255)),
                ('h', models.CharField(max_length=255)),
                ('bb_taskpath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.TaskPathBoundingBox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
