# Generated by Django 2.2.7 on 2020-01-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_taskpathboundingbox_taskprocesseddataboundingbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpath',
            name='taskPath',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='taskpathboundingbox',
            name='bb_taskPath',
            field=models.CharField(max_length=2550),
        ),
    ]
