# Generated by Django 2.2.7 on 2019-12-07 18:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='credits',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=20),
        ),
    ]
